### ISSUE TITLE
Unable to right-click and fill

### ISSUE THREAD

**Issue by NondescreptUser** [sarahavilov/autofillforms-e10s#11]
The new version doesn't allow the user to right-click, select the value to be filled, and then fill the blank with the selected value. Since that is the only way I ever used the old version (to fill blanks in forms that are either incorrectly tagged or not tagged at all - I already have a form-filler extension that fills in tagged forms far better than this one, and encrypts the stored data as well, for greater safety) the new version is currently of no use for me. I need to be able to right-click and choose the data value to fill in the blank.

**Comment by sarahavilov** [comment]
>  I need to be able to right-click and choose the data value to fill in the blank.

We already have it in right click! There is a context menu called "AutoFill" which displays all the saved items.

**Comment by sarahavilov** [comment]
>  I already have a form-filler extension that fills in tagged forms far better than this one

If you provide a sample page which this extension has problem with, I can fix this

**Comment by NondescreptUser** [comment]
OK, I was confused b/c you said somewhere that right-click filling was 'being deprecated' in the new version. So I thought you were planning on discontinuing right-click fill in the future. I'm glad to hear you're keeping it.
