### ISSUE TITLE
Way to use current domain in field value?

### ISSUE THREAD

**Issue by indextwo** [sarahavilov/autofillforms-e10s#12]
I couldn't find any solid documentation on it, but: is there a way to populate a given field with the _current website's_ domain? If I'm ever purchasing something or required to sign up, I almost always put `[name-of-website]@my-domain.net`, so that I know exactly where my mail is coming from (and later, if they've sold my address and/or been hacked). 

I've been hoping for this functionality for a while. Is there a way to do this with regex rules?

**Comment by sarahavilov** [comment]
I added two new reserved worlds; `_url_` and `_host_`. These two will be replaced with url or host name of current frame.

You can try this on the latest dev. https://github.com/sarahavilov/autofillforms-e10s/blob/master/builds/packed/chrome.zip
