### ISSUE TITLE
Can't remove default rules

### ISSUE THREAD

**Issue by Ileca** [sarahavilov/autofillforms-e10s#3]
Self-explanatory title. I can remove my own custom rules but can't remove the default ones even though there is a button for it.

**Comment by sarahavilov** [comment]
Correct, the default rules are not removable. If you click on the remove button, they should reset to the default value/rule. This is for optimization purpose.

I am going to add a note in the options page to clear this for users.
![screen shot 2016-06-25 at 13 43 05](https://cloud.githubusercontent.com/assets/12985412/16355899/1bc53280-3adb-11e6-9062-ff6188446ce8.png)

**Comment by Ileca** [comment]
I would suggest you to let us delete those default rules in non default profiles. It forces us to scroll down a bunch of useless rules before we saw ours and you bring the risk of collisions. Maybe, I didn't try so maybe it won't if you prioritized bottom regex rule.

**Comment by sarahavilov** [comment]
As of version 0.1.2, it is possible to delete default rules in the profile section.

Thanks for the report.
